### PR TITLE
remove daily summaries, and options page (nothing else is customisable)

### PR DESCRIPTION
**Pull request by psimyn**
remove Daily Summary - now just checks once/minute for new notifications

deleted options page - probably worth updating Chrome Store Description to reflect lack of customisation options (or can re-add the options page with custom notification styles or something...)

### CODE REVIEW

**Comment by geeknam** [comment]
Tested?

**Comment by geeknam** [comment]
@psimyn This has been uploaded as v1.2.8, please let everyone know.

**Comment by psimyn** [comment]
Thanks @geeknam - updated card, also submitted new PR with small bugfix (options icon still in popup). Apologies

**Comment by geeknam** [comment]
Sorry, I have no access to my laptop til 16th, the next PR might need to wait.

**Pull request merged**
